# ===== 개발 환경 (로컬 PC -> EC2 DB 직접 접속) =====

server.port=80

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://13.209.76.47:3306/couzldb
spring.datasource.username=couzl
spring.datasource.password=couzl1234

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
